src/assets/icons/warning.svg, src/components/MaAlert/MaAlert.scss, src/components/MaButton/MaButton.scss, src/components/MaButton/components/MaButtonSpinner.scss, src/components/MaCard/MaCard.scss, src/components/MaDatagrid/MaDatagrid.scss, src/components/MaDatagrid/components/MaDatagridArrow.vue, src/components/MaDatagrid/components/MaDatagridLoader.scss, src/components/MaGridContainer/stories.scss, src/components/MaOption/MaOption.scss, src/components/MaOption/MaOptionCheckbox.scss, src/components/MaOption/MaOptionRadio.scss, src/components/MaPagination/MaPagination.scss, src/components/MaPill/MaPill.scss, src/components/MaRange/MaRange.scss, src/components/MaSelect/MaSelect.scss, src/components/MaSidebar/MaSidebar.scss, src/components/MaText/MaText.scss, src/components/colors.stories.js, src/scss/_margarita-tokens.scss, src/scss/functions/_colors.scss, src/scss/mixins/_gradient-image.scss, src/scss/variables/_colors.scss
Closes #254. This is obviously a huge breaking change 😄 
---
The proposal here is to use color maps to rely on way less variable names. This will make color usage way more simple (no more "Is this primrose? tundora? pippin" but rather "this is pink dark").
To do so, we leverage Sass' maps (a.k.a. arrays 🤷) to handle hues and variations.
New colors map: https://github.com/holaluz/margarita/blob/colors/src/scss/variables/_colors.scss
New  get-color function: https://github.com/holaluz/margarita/blob/colors/src/scss/functions/_colors.scss#L7
Result:
(_disclaimer: color ordering in this storybook screenshot is soooo poor, but I didn't want to spend much time there. Since colors are properly organized in Figma, we can easily check them out there_).
---
Out of Scope:
- gradients
- shadows
- …
=> Update colors to match Design System

.storybook/colors.scss, package-lock.json, package.json, src/components/colors.stories.js, src/scss/variables/_colors.scss
This PR fixes an issue with the generated CSS (see the following [thread in slack](https://holaluz.slack.com/archives/C019DLZTBU6/p1600701743003300?thread_ts=1600675842.001100&cid=C019DLZTBU6)).
tl;dr: some sass loader was transforming `white-base` to `#fff-base`, thus breaking the `:export` statement. Since that statement was only meant to provide colors to the storybook story, I removed it from the CSS output and put it back inside storybook.
Also I took the liberty to improve the colors page _a bit_:
=> Fix: fix color CSS output

.browserslistrc
From this:
to this:
🎉 
10 KiB of CSS removed by excluding the following browers:
```
bb 10 (Blackberry Browser)
bb 7
ie 10 (Internet Explorer – obviously)
ie_mob 11 Internet Explorer Mobile (I didn't even know this was a thing)
ie_mob 10 (Opera Mobile)
op_mob 12.1
```
all browsers above are listed as dead ("dead" as in "_browsers without official support or updates for 24 months_"), so we should not be supporting them – even IE 10, which I believe we're already not supporting given the features we're currently using.
I suggest we created a shared browserslist config. Sadly enough Browserslist do not support `.js` config files so we can't simply add it on `npm-scripts`. Their docs suggest [creating a npm package](https://github.com/browserslist/browserslist#shareable-configs), but I'd like …
=> fix(perf): Remove support for dead browsers 

jsconfig.json, types/vue.d.ts
Looks like some path weren't properly set due to include/exclude, and VSC was complaining about unreachable paths. I followed [docs](https://code.visualstudio.com/docs/languages/jsconfig) and now it looks good.
I also removed the unused Vue.options types, as we're not really using them.
=> chore: Fix jsconfig warnings

package.json
`postinstall` runs after every installation (regardless of being local or from npm) so it is breaking v7 installation.
=> fix: Do not run style-dictionary on prod installation

.gitignore, package-lock.json, package.json
This PR adds a first iteration of the component autocompletion & intellisense that Vetur can offer.
It yields the following result:
It doesn't add "values" or description for each prop. This needs to be done manually by adding JSDoc comments to each prop. [Here](https://github.com/CyCraft/vue-intellisense/blob/production/packages/scripts/test/helpers/BlitzForm.vue#L9) you have an example of available fields.
btw, these JSDoc comments will also be used by Storybook or any other platform to document components, so work done there will be used everywhere and will become the source of truth for props documentation. Quite neat.
=> feat: Autogenerate component & prop autocompletion for Margarita components

.gitignore, package.json, src/index.js, style-dictionary.config.js
This PR adds CSS custom property to the Margarita CSS output. This is yet another step in the direction of replacing SCSS (#298), and will help us avoid using it in new projects such as nuxt-clean.
---
For the record, this is the output CSS:
```css
:root {
--color-pink-light: #f8b0cb;
--color-pink-base: #e6007d;
--color-pink-dark: #b3005d;
--color-green-light: #e2f3ad;
--color-green-base: #237b01;
--color-green-dark: #1f6d4a;
--color-yellow-light: #fdf6dd;
--color-yellow-base: #f5d154;
--color-yellow-dark: #ffba03;
--color-blue-light: #daf4fa;
--color-blue-base: #296c89;
--color-red-light: #ffdddc;
--color-red-base: #cb1010;
--color-brown-light: #f9f8f3;
--color-brown-base: #c8c0ab;
--color-orange-base: #f06c17;
--color-turquoise-base: #24b578;
--color-gray-lighter: #f6f6f6; …
```
=> feat: Generate CSS custom properties

src/components/MaAlert/MaAlert.scss, src/components/MaButton/MaButton.scss, src/components/MaCard/MaCard.scss, src/components/MaDatagrid/MaDatagrid.scss, src/components/MaDatagrid/components/MaDatagridLoader.scss, src/components/MaOption/MaOption.scss, src/components/MaOption/MaOptionCheckbox.scss, src/components/MaOption/MaOptionRadio.scss, src/components/MaPagination/MaPagination.scss, src/components/MaPill/MaPill.scss, src/components/MaRange/MaRange.scss, src/components/MaSelect/MaSelect.scss, src/components/MaSidebar/MaSidebar.scss, src/components/MaTextField/MaTextField.scss, src/components/MaTextField/MaTextField.stories.js
On the quest to progressively reduce the usage of SCSS, this PR removes the dreaded `rem()` function, which was not that helpful.
Notice that the function is still exposed for consumers to use, so this is not a breaking change.
Also, I tweaked some values to make them closer to what's in the Figma file of the Design System, so I think we could issue a release.
=> fix: Remove rem function usage

.browserslistrc
Looks like we were still supporting IE here in margarita even though it is not a browser we decided to support.
Before:
After:
🚀 
---
FYI, list of currently supported browsers (at least in margarita):
```bash
$ npx browserslist                        
and_chr 86
and_ff 82
and_qq 10.4
and_uc 12.12
android 81
baidu 7.12
chrome 86
chrome 85
edge 86
edge 85
firefox 82
firefox 81
ios_saf 14
ios_saf 13.4-13.7
ios_saf 12.2-12.4
kaios 2.5
op_mini all
op_mob 59
opera 72
opera 71
safari 14
safari 13.1
samsung 12.0
samsung 11.1-11.2
```
=> fix(perf): Remove (unwanted) support for any IE browser

src/components/MaStack/MaStack.spec.js, src/components/MaStack/MaStack.vue, vetur/attributes.json
This PR adds a `fill` value for the `align` prop on MaStack.
Thing is, align prop is currently optional and sets its default value to null. Turns out not setting any value yields a different behavior that setting `align="left"`, which _looks like_ the default value.
[See this codesandbox](https://codesandbox.io/s/cool-snyder-ph62f?file=/src/App.vue) to check what's going on.
The simplest way of handling this situation without introducing any breaking changes is by making the currently null value explicit – that is, creating a prop value that yields the same result (justify-items: stretch) as not setting the prop whatsoever. This makes the component more explicit and allows for responsive behaviors (`:align="[ 'fill', 'left' ]"`)
=> feat(Stack): Add fill value for align prop

src/components/MaModal/MaModal.css, src/components/MaModal/MaModal.vue
Weirdly enough, Modal works fine on Storybook, but looks like it is not properly placed when used somewhere else ([here]( https://deploy-preview-379--maitai.netlify.app/es/)).
I simply added the same `top` value the animation was setting – but looks like it does the trick in Maitai. It displays the Modal where it belongs while also animating it.
Re z-index, we discussed this is the simplest solution for now. I've left a comment to make sure we understand this is a quick&dirty fix, and not something we should rely on ;)
Any additional test would be appreciated!
=> fix: Add missing top placement and default z-index for Modal

docs/tokens/spacing.stories.mdx, src/components/MaHeading/MaHeading.vue, src/components/MaStack/MaStack.vue, src/components/MaText/MaText.vue, vetur/attributes.json
Documentation page link -> https://601199d127273f0021b037b0-qyeivtvayb.chromatic.com/?path=/story/tokens-spacing--page
- Same page for 'canvas' and 'docs' page -> just maintain one file/documentation (shall we do the same with the colors and the other tokens?)
- Still need to figure out how to use our components in MDX (I would like to use `MaStack` here) 🆘 
Stop checking on `margarita` the relation between token/prop namings and actual spacing size 💯
=> docs: Add Spacing tokens doc

src/components/MaModal/MaModal.css, src/components/MaModal/MaModal.vue
- Fixes https://github.com/holaluz/margarita/issues/366
- Fixes https://github.com/holaluz/margarita/issues/357
- Uses MaHeading for the Heading.
- Fixes focus trap bug when there are no focusable elements inside ModalContent.
- The modal header white has now less padding because it was a bit ugly.\
- Modifies the close icon a bit so it looks more like the one in figma
=> fix: MaModal responsiveness, UX & styling issues

.storybook/preview.js, docs/components/MaLayout.docs.mdx, package-lock.json, package.json, src/components/MaColumns/MaColumns.spec.js, src/components/MaColumns/MaColumns.stories.js, src/components/MaColumns/MaColumns.vue, src/components/MaColumns/index.js, src/components/MaLayout/MaLayout.spec.js, src/components/MaLayout/MaLayout.stories.js, src/components/MaLayout/MaLayout.vue, src/components/MaLayout/examples/DemoBlock.js, src/components/MaLayout/examples/examples.stories.js, src/components/MaLayout/index.js, src/components/MaStack/MaStack.spec.js, src/components/MaStack/MaStack.stories.js, src/components/MaStack/MaStack.vue, src/index.js, vetur/attributes.json, vetur/tags.json
This PR closes #274 
^ any help with missing steps will be greatly appreciated! And woud help people understand the components better…
=> feat: Add layout components

src/components/MaOption/MaOption.vue, src/components/MaOption/MaOptionCheckbox.css, src/components/MaOption/MaOptionRadio.css
Closes #346 
After gathering a bit of info, I do believe that having a property that allows the `MaOption` to be 'small' does not have lot of sense, because looking at the Design System, we only have **one approach** of the Checkbox and Radio input elements.
[Radio styles in the DS](https://www.figma.com/file/7RhweKibaUnxX6WYBl7zKW/Design-System-Beta?node-id=3540%3A6520)
[Checkbox styles in the DS](https://www.figma.com/file/7RhweKibaUnxX6WYBl7zKW/Design-System-Beta?node-id=3540%3A6348)
This being said, it kinda makes sense to just one approach, the one that we have in our DS (which basically means that the text we use as description should be `small` sized)
Checkbox:
Radio:
Example with a multi-line checkbox:
=> fix: Fix MaOption vertical alignment

src/components/MaColumns/MaColumns.vue, src/components/MaLayout/MaLayout.spec.js, src/components/MaStack/MaStack.spec.js, src/components/MaStack/MaStack.vue
This fixes a bug where, by setting a class with scoped styles to a layout component, the css doesn't work.
This happened because if we have a scoped css in the parent component and also in the functional component, the data attribute of the HTML element gets overwritten by the css in the functional component.
Because of this, all parent scoped css stops working.
The solution? Stop using scoped css in functional components.
=> fix: scoped styles in layout

src/components/MaTextField/MaTextField.css
Closes #382 
From:
To:
---
Now, this could be seen as a breaking change because some layouts might change. I'd say, though, that the expectation is that MaTextField would take all available space, so not having this behavior was a bug.
Thoughts?
=> fix: Make MaTextField fluid

src/components/MaOption/MaOptionRadio.css
UI components should not interfere with external positioning/laying out – it is on Layout components to handle it.
This PR removes the additional padding surrounding every `MaOption`, which breaks the DS-based designs when using them.
Bear in mind that this might change some layouts.
=> fix: Remove padding from MaOption

src/components/MaHeading/MaHeading.stories.js, src/components/MaHeading/MaHeading.vue, src/components/MaText/MaText.css, src/components/MaText/MaText.vue
Fixes https://github.com/holaluz/margarita/issues/372 (I think). I have tried it with `npm link` and everything seems to work in `dry-martini`, but I honestly don't know why.
I made the components functional and removed their scoped css so that the attribute for the scoped css doesn't get overwritten like it happened with ma-layout -> https://github.com/holaluz/margarita/pull/376 .
=> fix: make ma-text & ma-heading functional

src/css/partials/ciutadella.css
Let's not have fonts for browsers that we do not support.
Source: https://medium.com/@aitareydesign/understanding-of-font-formats-ttf-otf-woff-eot-svg-e55e00a1ef2
=> chore: do not load legacy fonts

src/components/MaOption/MaOption.spec.js, src/components/MaOption/MaOption.stories.js, src/components/MaOption/MaOption.vue, src/components/MaOption/MaOptionCheckbox.css, src/components/MaOption/MaOptionRadio.css, vetur/attributes.json, vetur/tags.json
These two props solve the text alignment issue in call me component. 
Cause for an specific size text will be a margin-top to align the text with the checkbox.
Current issue in kali:
We are duplicating the ma-text component in call me, the first one is being used by the ma-option and the second one is being used to apply size and tone. The second one is making issues with the positioning so with this PR we could remove one
=> feat: Add size and tone props to ma-option

docs/components/MaAlert.docs.mdx, src/components/MaAlert/MaAlert.css, src/components/MaAlert/MaAlert.spec.js, src/components/MaAlert/MaAlert.stories.js, src/components/MaAlert/MaAlert.vue, vetur/attributes.json, vetur/tags.json
After a [design review, new updates related to styling](https://www.figma.com/file/7RhweKibaUnxX6WYBl7zKW/Design-System?node-id=5314%3A1401) are coming:
- Title font-size -> 20px
- Body font-size -> 16px
- Link styling (depending on alert type, underlined by default, not underlined in hover)
- Remove alert size prop:
- Type prop would be removed.
- Default size would be current medium. (It only affects to padding size)
- Add new doc
=> feat: Update alert styling and remove size prop

src/components/MaText/MaText.vue
I do believe setting a `p` as a default element for MaText is the "expected" value when using the component. I'm not entirely sure why we decided to go with a `span` element to start with (maybe because a "text" is not the same thing as a "paragraph"?) but I still believe this change is an improvement.
---
Now, this is a breaking change. What do you think is the scope for it? Fixing it is as simple as removing `tag="p"` from MaText, and adding `tag="span"` on MaTexts without the prop.
=> feat(MaText): Set P as default value for MaText' tag

src/components/MaColumns/MaColumns.spec.js, src/components/MaColumns/MaColumns.vue, src/components/MaStack/MaStack.spec.js, src/components/MaStack/MaStack.vue
Closes #388.
With this change, postcss is able to detect the `gap` property and add the appropriate fallback for shitty browsers:
_(screenshot from dist/margarita.css)_
=> fix: Add gap support for older browsers

src/components/MaList/MaList.stories.js, src/components/MaOption/MaOption.vue
Related to https://github.com/holaluz/margarita/issues/409
Hello all,
I guess after setting the tag="p" in ma-text as default the maOption is broken when you try to align img + text (please see the image below). This pr is to fix it.
=> fix: MaOption set span as default tag

src/components/MaCard/MaCard.css, src/components/MaCard/MaCard.vue, vetur/attributes.json, vetur/tags.json
As now we have Ma-Layout and Ma-Stack we don't need the `has-padding-top` anymore, so this PR removes the prop to prevent its usage.
It's a breaking change, but a "little" one, it's only used 9 times only in Bonasera.
I'm not sure how to tag this release, fix with breaking change in the comment to release a major version?
=> feat(MaCard): Remove has-padding-top from

src/components/MaTextField/MaTextField.vue, vetur/attributes.json, vetur/tags.json
Looks like passing attrs does not allow us to simply set `<ma-text-field disabled>`, only `:disabled="true"`, because otherwise it does not append the `.ma-text-field__input-wrapper--disabled` class. With the proposed fix, both of these options work:
```vue
<ma-text-field disabled />
<ma-text-field :disabled="true" />
```
=> fix(MaTextField): Allow using disabled as prop

src/components/MaAlert/MaAlert.vue, src/components/MaOption/MaOption.vue
Hi all,
This PR is to scope the styles from Ma-alert #401  because we are overlapping other component styles (as the RadioQuestions commented on the [issue before](https://github.com/holaluz/margarita/issues/409)). Also, I removed the tag defined previously to fix the MaOption because is not doing anything it should be solved with this fix.
=> fix: scope styles in MaAlert 

.storybook/preview.js, docs/introduction/color-system.stories.mdx
This PR is to test the figma embeds in our docs.
You can se the example in the **Introduction category** --> **Color System** (you will need to scroll down)
Process:
To get the correct link we need to group the elements we want to show in FIGMA. Otherwise, the embed will show all the page.
Will be interesting to  confirm that url created in FIGMA will remain exactly the same after the Figma release
Please share your opinions :)
=> docs: add figma embed color to docs

docs/components/MaCard.docs.mdx, src/components/MaCard/MaCard.spec.js
Add emded docs for MaCard component from Figma. I've also added some basic tests. It is related to [this](https://holaluz.kanbanize.com/ctrl_board/65/cards/23083/details/) Kanbanize card.
- [Link en Figma](https://www.figma.com/proto/7RhweKibaUnxX6WYBl7zKW/%E2%9A%A1%EF%B8%8F-Watt-Design-System?embed_host=share&hotspot-hints=0&kind=&node-id=5664%3A338&page-id=5314%3A1402&scaling=scale-down-width&viewport=1280%2C446%2C0.48540157079696655&hide-ui=1)
- [Docu en Notion](https://www.notion.so/holaluz/a1cb451d360941d98f08831cf679edab?v=f7024af195d34caface8649e58f98c12&p=c50116a66ba844b7b3398abcdb0088da)
=> docs: add-ma-card-docs
