README.md
Not that anyone is expected to use it, but it takes little-to-no-effort to make things right 😉
=> Improve readme now that Margarita is a public repo

src/components/MaGridContainer/MaGridContainer.stories.js, src/components/MaText/index.js, src/components/MaTextField/MaTextField.scss, src/components/MaTextField/MaTextField.spec.js, src/components/MaTextField/MaTextField.stories.js, src/components/MaTextField/MaTextField.vue, src/components/MaTextField/index.js, src/index.js
Closes #278 
---
If there are any other breaking changes regarding MaText(Field), now is a great time to bring them up 😉 
Also, I reordered stories a bit. There's still a lot of room for improvement
=> Rename MaText to MaTextField

src/components/MaButton/MaButton.scss, src/components/MaButton/MaButton.stories.js, src/components/MaButton/MaButton.vue
Remove unused & misleading `fluid` prop from MaButton.
=> Remove fluid prop from MaButton

README.md
Add minimal docs on how to handle Nuxt installation.
=> docs: Add docs to install in nuxt

package-lock.json, package.json, release.config.js
Not 100% sure it'll work until this gets merged, so XD
=> chore: Send Slack notification on new release

jest.config.js, package-lock.json, src/components/MaButton/MaButton.spec.js
Fixes some problems that appeared in https://github.com/holaluz/kalimotxo, which shares the exact same `jest.config.js` as margarita.
More info: https://holaluz.slack.com/archives/CR9670R5H/p1606311768011300
Bonus: fix lint errors in `MaButton` test
=> chore: fix jest .vue imports & "too many files" issue

.github/workflows/ci.yml, .github/workflows/deploy.yml, .github/workflows/release.yml
=> chore: Add build step to CI + cleanup

package-lock.json, package.json, src/components/MaModal/MaModal.scss, src/components/MaModal/MaModal.stories.js, src/components/MaModal/MaModal.vue
I'm not getting the `modal` and `overlay` transitions to work at different times.
We have looked at [Vue's ](https://vuejs.org/v2/guide/transitions.html)docu but it is not working. We also tried to make a `transition-group`, but it didn't work either).
If anyone wants to try it, I'll upload the changes. I will keep trying today.
=> Review modal styles

src/components/MaButton/MaButton.css, src/components/MaModal/MaModal.css, src/components/MaRange/MaRange.css
I know we're missing some gradient variables (https://github.com/holaluz/margarita/issues/276), but for now I think it make sense to simply fix the ones from margarita.
=> fix: Fix gradients direction and tone

.gitignore, lint-staged.config.js, package.json, src/css/tokens.css, src/scss/_tokens.scss, vetur/attributes.json, vetur/tags.json
=> chore: Include vetur folder and design tokens back to git

src/components/MaAlert/MaAlert.spec.js, src/components/MaButton/MaButton.spec.js, src/components/MaDatagrid/MaDatagrid.spec.js, src/components/MaHeading/MaHeading.spec.js, src/components/MaHidden/MaHidden.spec.js, src/components/MaModal/MaModal.spec.js, src/components/MaOption/MaOption.spec.js, src/components/MaPagination/MaPagination.spec.js, src/components/MaRange/MaRange.spec.js, src/components/MaSelect/MaSelect.spec.js, src/components/MaStack/MaStack.spec.js, src/components/MaText/MaText.spec.js, src/components/MaTextField/MaTextField.spec.js, src/directives/markdown/markdown.spec.js, src/margarita-test-utils.js
So we don't need to initialize Margarita env (with responsible plugin and so on) every time.
=> chore: Abstract render function for tests

docs/components/MaModal.docs.mdx, docs/introduction/welcome.stories.mdx
This is the first iteration for documenting components, so it will be super helpful if you can give me feedback about the template I'm proposing (Description, How to use it (this will be related to the controls), When to use it, and Behavior). Also, anything you find confusing or any additions will be more than welcomed!
PS: This is my first PR in Holaluz. Please, be kind 😆
=> docs: Update modal documentation

src/components/MaRange/MaRange.css, src/components/MaRange/MaRange.vue, src/components/MaSelect/MaSelect.css, src/components/MaSelect/MaSelect.vue, src/components/MaTextField/MaTextField.css, src/components/MaTextField/MaTextField.stories.js, src/components/MaTextField/MaTextField.vue
…to fix alignment when used in conjunction with other MaText components. Related to https://holaluz.slack.com/archives/CR9670R5H/p1614869238064300
=> fix: Fix alignment when using MaText and input components

src/components/MaTextField/MaTextField.css, src/components/MaTextField/MaTextField.stories.js
=> feat: remove arrows from input type number

src/components/MaContainer/MaContainer.spec.js, src/components/MaContainer/MaContainer.stories.js, src/components/MaContainer/MaContainer.vue, src/components/MaContainer/index.js, src/index.js, vetur/attributes.json, vetur/tags.json
=> feat: add MaContainer

src/components/MaPill/MaPill.css, src/components/MaPill/MaPill.stories.js, src/components/MaPill/MaPill.vue, vetur/attributes.json
A new color has been added to Figma's DS
=> feat: Add MaPill pink color

src/components/MaCard/MaCard.css, src/components/MaCard/MaCard.vue, vetur/attributes.json, vetur/tags.json
This reverts commit 460284deb71ddbd20ae61c5d29965609a2336234.
=> Revert "Remove prop (#411)"

src/components/MaCard/MaCard.css, src/components/MaCard/MaCard.vue, vetur/attributes.json, vetur/tags.json
This PR is approved here: https://github.com/holaluz/margarita/pull/411
I just forgot the semantic release.
Sorry, I'm such a disaster
=> Remove has-padding-top prop from Ma-Card

src/components/MaList/MaList.css, src/components/MaList/MaList.spec.js, src/components/MaList/MaList.stories.js, src/components/MaList/MaList.vue, vetur/attributes.json, vetur/tags.json
and modify css so the icon is not centered vertically
=> feat: Add prop space to MaList

docs/components/form-elements/MaSelect.docs.mdx
Update MaSelect Figma link to embed in Docs tab according to [the reference spreadsheet](https://docs.google.com/spreadsheets/d/1sY-g4wNY33Y132HzJF5ggXGXaATrorsGipsymGyK_OQ/edit?ts=60a7e623#gid=0)
=> docs: Update MaSelect embed

src/css/tokens.css, src/scss/_tokens.scss, src/tokens/shadow.js
spec: https://www.figma.com/file/7RhweKibaUnxX6WYBl7zKW/%E2%9A%A1%EF%B8%8F-Watt-Design-System?node-id=5314%3A807
=> feat: Update shadow tokens
